### ISSUE TITLE
Backend Storage for Token Images

### ISSUE THREAD

**Issue by tign227** [Novaro-Labs/novaro-server#21]
* Implement backend storage for user-uploaded images during token creation.
* Ensure the stored images are correctly associated with each token.
* Enable the images to be displayed alongside the tokens in the frontend.
<img width="400" alt="截屏2024-11-01 08 07 17" src="https://github.com/user-attachments/assets/69d794e9-3b60-4cf1-9aa6-66a01d98d7a2">
<img width="400" alt="截屏2024-11-01 08 08 12" src="https://github.com/user-attachments/assets/14502945-fcc5-4745-a1ee-f05a223d2c9b">

**Comment by jalins** [comment]
upload image: 
uri:  v1/api/upload/files
method: post(form-data)
params: images、sourceId

get image:
uri: v1/api/upload/getTokenImg?sourceId=
method: get

**Comment by tign227** [comment]
generate unique source ID for image

**Comment by jalins** [comment]
calculate hash of file content as sourceId, for example:
{
    "code": 200,
    "data": [
        {
            "id": "7d38292664234b80a238de5118426e3a",
            "path": "assets/20241104/1730702274678236000.jpg",
            "sourceId": "6343b393cb7e207cc6125089fff87737397678d04fe397a08b27cc66710868ca",
            "createdAt": "2024-11-04T14:37:54.678591+08:00"
        }
    ],
    "msg": "success"
}
